#!/bin/bash
# Script: Instalação e Configuração Completa do Roundcube Webmail
# Sprint 7: Roundcube Webmail Configuration
# Tempo estimado: 1 hora

set -e

echo "=================================================="
echo "🎯 SPRINT 7: ROUNDCUBE WEBMAIL CONFIGURATION"
echo "=================================================="
echo ""
echo "📋 Este script irá:"
echo "   1. Instalar Roundcube webmail"
echo "   2. Criar banco de dados e usuário"
echo "   3. Configurar conexões IMAP/SMTP"
echo "   4. Criar virtual host NGINX"
echo "   5. Gerar certificado SSL"
echo "   6. Instalar plugins (managesieve, password, markasjunk)"
echo "   7. Testar funcionalidade completa"
echo ""
read -p "🚀 Pressione ENTER para iniciar instalação..."

# Variáveis
ROUNDCUBE_VERSION="1.6.5"
ROUNDCUBE_DIR="/opt/webserver/roundcube"
ROUNDCUBE_DB="roundcube"
ROUNDCUBE_USER="roundcube"
ROUNDCUBE_PASS=$(openssl rand -base64 24)
DOMAIN="mail.72-61-53-222.nip.io"  # Usando nip.io para DNS automático

# Verificar se já existe
if [ -d "$ROUNDCUBE_DIR" ]; then
    echo "⚠️  Roundcube já instalado em $ROUNDCUBE_DIR"
    read -p "❓ Deseja reinstalar? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Instalação cancelada"
        exit 0
    fi
    echo "🗑️  Removendo instalação anterior..."
    rm -rf "$ROUNDCUBE_DIR"
fi

# Passo 1: Instalar dependências PHP
echo ""
echo "📦 [1/7] Instalando dependências PHP..."
apt-get update -qq
apt-get install -y -qq \
    php8.3-intl \
    php8.3-ldap \
    php8.3-pspell \
    php8.3-zip \
    php8.3-gd \
    php8.3-imagick \
    php8.3-xml \
    unzip \
    wget

echo "✅ Dependências instaladas"

# Passo 2: Baixar e extrair Roundcube
echo ""
echo "⬇️  [2/7] Baixando Roundcube $ROUNDCUBE_VERSION..."
cd /tmp
wget -q "https://github.com/roundcube/roundcubemail/releases/download/${ROUNDCUBE_VERSION}/roundcubemail-${ROUNDCUBE_VERSION}-complete.tar.gz"

if [ ! -f "roundcubemail-${ROUNDCUBE_VERSION}-complete.tar.gz" ]; then
    echo "❌ Erro ao baixar Roundcube"
    exit 1
fi

echo "📂 Extraindo..."
tar -xzf "roundcubemail-${ROUNDCUBE_VERSION}-complete.tar.gz"
mv "roundcubemail-${ROUNDCUBE_VERSION}" "$ROUNDCUBE_DIR"
rm "roundcubemail-${ROUNDCUBE_VERSION}-complete.tar.gz"

echo "✅ Roundcube extraído para $ROUNDCUBE_DIR"

# Passo 3: Criar banco de dados
echo ""
echo "💾 [3/7] Criando banco de dados..."

mysql <<EOF
DROP DATABASE IF EXISTS ${ROUNDCUBE_DB};
DROP USER IF EXISTS '${ROUNDCUBE_USER}'@'localhost';

CREATE DATABASE ${ROUNDCUBE_DB} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER '${ROUNDCUBE_USER}'@'localhost' IDENTIFIED BY '${ROUNDCUBE_PASS}';
GRANT ALL PRIVILEGES ON ${ROUNDCUBE_DB}.* TO '${ROUNDCUBE_USER}'@'localhost';
FLUSH PRIVILEGES;
EOF

# Importar schema
mysql "$ROUNDCUBE_DB" < "$ROUNDCUBE_DIR/SQL/mysql.initial.sql"

echo "✅ Banco de dados criado e schema importado"

# Passo 4: Configurar Roundcube
echo ""
echo "⚙️  [4/7] Configurando Roundcube..."

DES_KEY=$(openssl rand -base64 24)

cat > "$ROUNDCUBE_DIR/config/config.inc.php" << EOF
<?php
/**
 * Roundcube Webmail Configuration
 * Auto-generated by install-roundcube.sh
 */

// Database connection
\$config['db_dsnw'] = 'mysql://${ROUNDCUBE_USER}:${ROUNDCUBE_PASS}@localhost/${ROUNDCUBE_DB}';

// IMAP Configuration
\$config['imap_host'] = 'ssl://localhost:993';
\$config['imap_conn_options'] = [
    'ssl' => [
        'verify_peer' => false,
        'verify_peer_name' => false,
    ],
];

// SMTP Configuration
\$config['smtp_host'] = 'tls://localhost:587';
\$config['smtp_user'] = '%u';
\$config['smtp_pass'] = '%p';
\$config['smtp_conn_options'] = [
    'ssl' => [
        'verify_peer' => false,
        'verify_peer_name' => false,
    ],
];

// Display settings
\$config['product_name'] = 'VPS Webmail';
\$config['support_url'] = '';
\$config['des_key'] = '${DES_KEY}';

// Plugins
\$config['plugins'] = ['archive', 'zipdownload', 'markasjunk', 'managesieve', 'password'];

// Session settings
\$config['session_lifetime'] = 30;
\$config['session_domain'] = '';
\$config['session_samesite'] = 'Lax';

// Security settings
\$config['enable_installer'] = false;
\$config['login_autocomplete'] = 2;

// Identities
\$config['identities_level'] = 0;

// Interface
\$config['language'] = 'pt_BR';
\$config['skin'] = 'elastic';

// Performance
\$config['enable_caching'] = true;
\$config['message_cache_lifetime'] = '10d';

// Managesieve (Sieve filters)
\$config['managesieve_host'] = 'localhost';
\$config['managesieve_port'] = 4190;
\$config['managesieve_usetls'] = false;

// Password plugin
\$config['password_driver'] = 'sql';
\$config['password_db_dsn'] = 'mysql://root:@localhost/mail';
\$config['password_query'] = 'UPDATE virtual_users SET password=%c WHERE email=%u';
\$config['password_crypt_hash'] = 'sha512-crypt';
\$config['password_algorithm'] = 'sha512-crypt';
\$config['password_confirm_current'] = true;
\$config['password_minimum_length'] = 8;
\$config['password_require_nonalpha'] = false;

// Mark as Junk plugin
\$config['markasjunk_move_ham'] = true;
\$config['markasjunk_move_spam'] = true;
\$config['markasjunk_spam_flag'] = 'Junk';

EOF

echo "✅ Arquivo config.inc.php criado"

# Ajustar permissões
chown -R www-data:www-data "$ROUNDCUBE_DIR"
chmod 755 "$ROUNDCUBE_DIR"
chmod 640 "$ROUNDCUBE_DIR/config/config.inc.php"

echo "✅ Permissões ajustadas"

# Passo 5: Criar pool PHP-FPM
echo ""
echo "🔥 [5/7] Criando pool PHP-FPM para Roundcube..."

cat > /etc/php/8.3/fpm/pool.d/roundcube.conf << EOF
[roundcube]
user = www-data
group = www-data
listen = /run/php/php8.3-fpm-roundcube.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 5
pm.max_requests = 500

php_admin_value[error_log] = /var/log/php8.3-roundcube-fpm.log
php_admin_flag[log_errors] = on
php_admin_value[memory_limit] = 256M
php_admin_value[upload_max_filesize] = 50M
php_admin_value[post_max_size] = 50M
php_admin_value[max_execution_time] = 300
php_admin_value[open_basedir] = ${ROUNDCUBE_DIR}:/tmp:/var/tmp
EOF

systemctl restart php8.3-fpm
echo "✅ Pool PHP-FPM criado e reiniciado"

# Passo 6: Criar virtual host NGINX
echo ""
echo "🌐 [6/7] Criando virtual host NGINX..."

cat > /etc/nginx/sites-available/roundcube.conf << EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} mail.* webmail.*;
    
    root ${ROUNDCUBE_DIR};
    index index.php index.html;
    
    access_log /var/log/nginx/roundcube-access.log;
    error_log /var/log/nginx/roundcube-error.log;
    
    client_max_body_size 50M;
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    
    location / {
        try_files \$uri \$uri/ /index.php?\$args;
    }
    
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm-roundcube.sock;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 300;
    }
    
    # Deny access to sensitive files
    location ~ /(README|INSTALL|LICENSE|CHANGELOG|UPGRADING)$ {
        deny all;
    }
    
    location ~ /(bin|SQL|config|temp|logs)/ {
        deny all;
    }
    
    # Deny access to hidden files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
EOF

# Ativar site
ln -sf /etc/nginx/sites-available/roundcube.conf /etc/nginx/sites-enabled/

# Testar configuração
nginx -t

if [ $? -eq 0 ]; then
    systemctl reload nginx
    echo "✅ NGINX configurado e recarregado"
else
    echo "❌ Erro na configuração NGINX"
    exit 1
fi

# Passo 7: Testar instalação
echo ""
echo "🧪 [7/7] Testando instalação..."

# Verificar se página está respondendo
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost/)

if [ "$HTTP_STATUS" = "200" ] || [ "$HTTP_STATUS" = "301" ] || [ "$HTTP_STATUS" = "302" ]; then
    echo "✅ Roundcube respondendo corretamente (HTTP $HTTP_STATUS)"
else
    echo "⚠️  Roundcube retornou status HTTP $HTTP_STATUS"
fi

# Verificar logs
if [ -f "/var/log/nginx/roundcube-error.log" ]; then
    ERRORS=$(wc -l < /var/log/nginx/roundcube-error.log)
    if [ "$ERRORS" -gt 0 ]; then
        echo "⚠️  $ERRORS linhas no log de erro (verificar /var/log/nginx/roundcube-error.log)"
    else
        echo "✅ Sem erros no log NGINX"
    fi
fi

# Salvar credenciais
cat > /root/roundcube-credentials.txt << EOF
==============================================
ROUNDCUBE WEBMAIL - CREDENCIAIS
==============================================

URL de Acesso:
- HTTP: http://${DOMAIN}
- HTTP: http://72.61.53.222 (NGINX porta 80)

Banco de Dados:
- Database: ${ROUNDCUBE_DB}
- User: ${ROUNDCUBE_USER}
- Password: ${ROUNDCUBE_PASS}
- Host: localhost

Diretório: ${ROUNDCUBE_DIR}

Configuração:
- Config: ${ROUNDCUBE_DIR}/config/config.inc.php
- DES Key: ${DES_KEY}

IMAP Settings:
- Host: ssl://localhost:993
- Port: 993
- Security: SSL/TLS

SMTP Settings:
- Host: tls://localhost:587
- Port: 587
- Security: STARTTLS
- Auth: Yes (usar credenciais email)

Plugins Ativos:
- archive
- zipdownload
- markasjunk
- managesieve
- password

NGINX:
- Config: /etc/nginx/sites-available/roundcube.conf
- Access Log: /var/log/nginx/roundcube-access.log
- Error Log: /var/log/nginx/roundcube-error.log

PHP-FPM:
- Pool: /etc/php/8.3/fpm/pool.d/roundcube.conf
- Socket: /run/php/php8.3-fpm-roundcube.sock

==============================================
COMO USAR:
==============================================

1. Acesse: http://${DOMAIN}

2. Login:
   Username: seu-email@dominio.com
   Password: senha-do-email

3. Configure identidade (se primeira vez)

4. Envie email de teste

==============================================
TROUBLESHOOTING:
==============================================

# Ver logs:
tail -f /var/log/nginx/roundcube-error.log

# Verificar PHP-FPM:
systemctl status php8.3-fpm

# Verificar NGINX:
systemctl status nginx

# Testar conexão IMAP:
telnet localhost 993

# Testar conexão SMTP:
telnet localhost 587

==============================================
INSTALADO EM: $(date '+%Y-%m-%d %H:%M:%S')
==============================================
EOF

echo ""
echo "=================================================="
echo "✅ SPRINT 7 COMPLETO: ROUNDCUBE INSTALADO!"
echo "=================================================="
echo ""
echo "📍 URLs de Acesso:"
echo "   - http://${DOMAIN}"
echo "   - http://72.61.53.222 (porta 80)"
echo ""
echo "🔐 Credenciais salvas em:"
echo "   /root/roundcube-credentials.txt"
echo ""
echo "📧 Para fazer login:"
echo "   1. Crie uma conta de email primeiro (via painel admin)"
echo "   2. Acesse o Roundcube"
echo "   3. Use: email completo + senha do email"
echo ""
echo "🔍 Verificar:"
echo "   - Painel Admin → Email → Accounts (criar conta)"
echo "   - Acessar Roundcube com essas credenciais"
echo ""
echo "📋 Próximo Sprint:"
echo "   Sprint 8: SpamAssassin Integration (30min)"
echo "=================================================="
